add_test( [==[Saturation pressures water]==] /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest [==[Saturation pressures water]==]  )
set_tests_properties( [==[Saturation pressures water]==] PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( [==[Saturation pressures acids]==] /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest [==[Saturation pressures acids]==]  )
set_tests_properties( [==[Saturation pressures acids]==] PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( [==[Air properties]==] /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest [==[Air properties]==]  )
set_tests_properties( [==[Air properties]==] PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( [==[Particle dynamics]==] /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest [==[Particle dynamics]==]  )
set_tests_properties( [==[Particle dynamics]==] PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( Microphysics /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest Microphysics  )
set_tests_properties( Microphysics PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( Nucleation /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest Nucleation  )
set_tests_properties( Nucleation PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( [==[Build kernel]==] /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest [==[Build kernel]==]  )
set_tests_properties( [==[Build kernel]==] PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( Aerosol /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest Aerosol  )
set_tests_properties( Aerosol PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( [==[EPM integrate]==] /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest [==[EPM integrate]==]  )
set_tests_properties( [==[EPM integrate]==] PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( MetFunction /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest MetFunction  )
set_tests_properties( MetFunction PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( [==[Vortex Losses Survival Fraction]==] /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest [==[Vortex Losses Survival Fraction]==]  )
set_tests_properties( [==[Vortex Losses Survival Fraction]==] PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( [==[YamlInputReader Helper Functions]==] /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest [==[YamlInputReader Helper Functions]==]  )
set_tests_properties( [==[YamlInputReader Helper Functions]==] PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( [==[Read Yaml File]==] /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest [==[Read Yaml File]==]  )
set_tests_properties( [==[Read Yaml File]==] PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( [==[Generate All Cases]==] /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest [==[Generate All Cases]==]  )
set_tests_properties( [==[Generate All Cases]==] PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
add_test( [==[Generate Input Objects]==] /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests/unittest [==[Generate Input Objects]==]  )
set_tests_properties( [==[Generate Input Objects]==] PROPERTIES WORKING_DIRECTORY /home/chinahg/GCresearch/APCEMM/Code.v05-00/tests)
set( unittest_TESTS [==[Saturation pressures water]==] [==[Saturation pressures acids]==] [==[Air properties]==] [==[Particle dynamics]==] Microphysics Nucleation [==[Build kernel]==] Aerosol [==[EPM integrate]==] MetFunction [==[Vortex Losses Survival Fraction]==] [==[YamlInputReader Helper Functions]==] [==[Read Yaml File]==] [==[Generate All Cases]==] [==[Generate Input Objects]==])
